// By: Deepseek

enum ElementType: String {
    case grass
    case poison
    case fire
    case flying
    case water
    case bug
    case normal
    case electric
    case ground
    case fairy
    case psychic
    case rock
    case ice
    case dragon
    case dark
    case steel
    case fighting
    case ghost
}

struct Pokemon: Identifiable {
    var id: Int
    var name: String
    var types: [ElementType]
    var imageName: String
}

let pokemons: [Pokemon] = [
    Pokemon(id: 1, name: "bulbasaur", types: [.grass, .poison], imageName:"img_1"),
    Pokemon(id: 2, name: "ivysaur", types: [.grass, .poison], imageName:"img_2"),
    Pokemon(id: 3, name: "venusaur", types: [.grass, .poison], imageName:"img_3"),
    Pokemon(id: 4, name: "charmander", types: [.fire], imageName:"img_4"),
    Pokemon(id: 5, name: "charmeleon", types: [.fire], imageName:"img_5"),
    Pokemon(id: 6, name: "charizard", types: [.fire, .flying], imageName:"img_6"),
    Pokemon(id: 7, name: "squirtle", types: [.water], imageName:"img_7"),
    Pokemon(id: 8, name: "wartortle", types: [.water], imageName:"img_8"),
    Pokemon(id: 9, name: "blastoise", types: [.water], imageName:"img_9"),
    Pokemon(id: 10, name: "caterpie", types: [.bug], imageName:"img_10"),
    Pokemon(id: 11, name: "metapod", types: [.bug], imageName:"img_11"),
    Pokemon(id: 12, name: "butterfree", types: [.bug, .flying], imageName:"img_12"),
    Pokemon(id: 13, name: "weedle", types: [.bug, .poison], imageName:"img_13"),
    Pokemon(id: 14, name: "kakuna", types: [.bug, .poison], imageName:"img_14"),
    Pokemon(id: 15, name: "beedrill", types: [.bug, .poison], imageName:"img_15"),
    Pokemon(id: 16, name: "pidgey", types: [.normal, .flying], imageName:"img_16"),
    Pokemon(id: 17, name: "pidgeotto", types: [.normal, .flying], imageName:"img_17"),
    Pokemon(id: 18, name: "pidgeot", types: [.normal, .flying], imageName:"img_18"),
    Pokemon(id: 19, name: "rattata", types: [.normal], imageName:"img_19"),
    Pokemon(id: 20, name: "raticate", types: [.normal], imageName:"img_20"),
    Pokemon(id: 21, name: "spearow", types: [.normal, .flying], imageName:"img_21"),
    Pokemon(id: 22, name: "fearow", types: [.normal, .flying], imageName:"img_22"),
    Pokemon(id: 23, name: "ekans", types: [.poison], imageName:"img_23"),
    Pokemon(id: 24, name: "arbok", types: [.poison], imageName:"img_24"),
    Pokemon(id: 25, name: "pikachu", types: [.electric], imageName:"img_25"),
    Pokemon(id: 26, name: "raichu", types: [.electric], imageName:"img_26"),
    Pokemon(id: 27, name: "sandshrew", types: [.ground], imageName:"img_27"),
    Pokemon(id: 28, name: "sandslash", types: [.ground], imageName:"img_28"),
    Pokemon(id: 29, name: "nidoran-f", types: [.poison], imageName:"img_29"),
    Pokemon(id: 30, name: "nidorina", types: [.poison], imageName:"img_30"),
    Pokemon(id: 31, name: "nidoqueen", types: [.poison, .ground], imageName:"img_31"),
    Pokemon(id: 32, name: "nidoran-m", types: [.poison], imageName:"img_32"),
    Pokemon(id: 33, name: "nidorino", types: [.poison], imageName:"img_33"),
    Pokemon(id: 34, name: "nidoking", types: [.poison, .ground], imageName:"img_34"),
    Pokemon(id: 35, name: "clefairy", types: [.fairy], imageName:"img_35"),
    Pokemon(id: 36, name: "clefable", types: [.fairy], imageName:"img_36"),
    Pokemon(id: 37, name: "vulpix", types: [.fire], imageName:"img_37"),
    Pokemon(id: 38, name: "ninetales", types: [.fire], imageName:"img_38"),
    Pokemon(id: 39, name: "jigglypuff", types: [.normal, .fairy], imageName:"img_39"),
    Pokemon(id: 40, name: "wigglytuff", types: [.normal, .fairy], imageName:"img_40"),
    Pokemon(id: 41, name: "zubat", types: [.poison, .flying], imageName:"img_41"),
    Pokemon(id: 42, name: "golbat", types: [.poison, .flying], imageName:"img_42"),
    Pokemon(id: 43, name: "oddish", types: [.grass, .poison], imageName:"img_43"),
    Pokemon(id: 44, name: "gloom", types: [.grass, .poison], imageName:"img_44"),
    Pokemon(id: 45, name: "vileplume", types: [.grass, .poison], imageName:"img_45"),
    Pokemon(id: 46, name: "paras", types: [.bug, .grass], imageName:"img_46"),
    Pokemon(id: 47, name: "parasect", types: [.bug, .grass], imageName:"img_47"),
    Pokemon(id: 48, name: "venonat", types: [.bug, .poison], imageName:"img_48"),
    Pokemon(id: 49, name: "venomoth", types: [.bug, .poison], imageName:"img_49"),
    Pokemon(id: 50, name: "diglett", types: [.ground], imageName:"img_50"),
    Pokemon(id: 51, name: "dugtrio", types: [.ground], imageName:"img_51"),
    Pokemon(id: 52, name: "meowth", types: [.normal], imageName:"img_52"),
    Pokemon(id: 53, name: "persian", types: [.normal], imageName:"img_53"),
    Pokemon(id: 54, name: "psyduck", types: [.water], imageName:"img_54"),
    Pokemon(id: 55, name: "golduck", types: [.water], imageName:"img_55"),
    Pokemon(id: 56, name: "mankey", types: [.fighting], imageName:"img_56"),
    Pokemon(id: 57, name: "primeape", types: [.fighting], imageName:"img_57"),
    Pokemon(id: 58, name: "growlithe", types: [.fire], imageName:"img_58"),
    Pokemon(id: 59, name: "arcanine", types: [.fire], imageName:"img_59"),
    Pokemon(id: 60, name: "poliwag", types: [.water], imageName:"img_60"),
    Pokemon(id: 61, name: "poliwhirl", types: [.water], imageName:"img_61"),
    Pokemon(id: 62, name: "poliwrath", types: [.water, .fighting], imageName:"img_62"),
    Pokemon(id: 63, name: "abra", types: [.psychic], imageName:"img_63"),
    Pokemon(id: 64, name: "kadabra", types: [.psychic], imageName:"img_64"),
    Pokemon(id: 65, name: "alakazam", types: [.psychic], imageName:"img_65"),
    Pokemon(id: 66, name: "machop", types: [.fighting], imageName:"img_66"),
    Pokemon(id: 67, name: "machoke", types: [.fighting], imageName:"img_67"),
    Pokemon(id: 68, name: "machamp", types: [.fighting], imageName:"img_68"),
    Pokemon(id: 69, name: "bellsprout", types: [.grass, .poison], imageName:"img_69"),
    Pokemon(id: 70, name: "weepinbell", types: [.grass, .poison], imageName:"img_70"),
    Pokemon(id: 71, name: "victreebel", types: [.grass, .poison], imageName:"img_71"),
    Pokemon(id: 72, name: "tentacool", types: [.water, .poison], imageName:"img_72"),
    Pokemon(id: 73, name: "tentacruel", types: [.water, .poison], imageName:"img_73"),
    Pokemon(id: 74, name: "geodude", types: [.rock, .ground], imageName:"img_74"),
    Pokemon(id: 75, name: "graveler", types: [.rock, .ground], imageName:"img_75"),
    Pokemon(id: 76, name: "golem", types: [.rock, .ground], imageName:"img_76"),
    Pokemon(id: 77, name: "ponyta", types: [.fire], imageName:"img_77"),
    Pokemon(id: 78, name: "rapidash", types: [.fire], imageName:"img_78"),
    Pokemon(id: 79, name: "slowpoke", types: [.water, .psychic], imageName:"img_79"),
    Pokemon(id: 80, name: "slowbro", types: [.water, .psychic], imageName:"img_80"),
    Pokemon(id: 81, name: "magnemite", types: [.electric, .steel], imageName:"img_81"),
    Pokemon(id: 82, name: "magneton", types: [.electric, .steel], imageName:"img_82"),
    Pokemon(id: 83, name: "farfetchd", types: [.normal, .flying], imageName:"img_83"),
    Pokemon(id: 84, name: "doduo", types: [.normal, .flying], imageName:"img_84"),
    Pokemon(id: 85, name: "dodrio", types: [.normal, .flying], imageName:"img_85"),
    Pokemon(id: 86, name: "seel", types: [.water], imageName:"img_86"),
    Pokemon(id: 87, name: "dewgong", types: [.water, .ice], imageName:"img_87"),
    Pokemon(id: 88, name: "grimer", types: [.poison], imageName:"img_88"),
    Pokemon(id: 89, name: "muk", types: [.poison], imageName:"img_89"),
    Pokemon(id: 90, name: "shellder", types: [.water], imageName:"img_90"),
    Pokemon(id: 91, name: "cloyster", types: [.water, .ice], imageName:"img_91"),
    Pokemon(id: 92, name: "gastly", types: [.ghost, .poison], imageName:"img_92"),
    Pokemon(id: 93, name: "haunter", types: [.ghost, .poison], imageName:"img_93"),
    Pokemon(id: 94, name: "gengar", types: [.ghost, .poison], imageName:"img_94"),
    Pokemon(id: 95, name: "onix", types: [.rock, .ground], imageName:"img_95"),
    Pokemon(id: 96, name: "drowzee", types: [.psychic], imageName:"img_96"),
    Pokemon(id: 97, name: "hypno", types: [.psychic], imageName:"img_97"),
    Pokemon(id: 98, name: "krabby", types: [.water], imageName:"img_98"),
    Pokemon(id: 99, name: "kingler", types: [.water], imageName:"img_99"),
    Pokemon(id: 100, name: "voltorb", types: [.electric], imageName:"img_100"),
    Pokemon(id: 101, name: "electrode", types: [.electric], imageName:"img_101"),
    Pokemon(id: 102, name: "exeggcute", types: [.grass, .psychic], imageName:"img_102"),
    Pokemon(id: 103, name: "exeggutor", types: [.grass, .psychic], imageName:"img_103"),
    Pokemon(id: 104, name: "cubone", types: [.ground], imageName:"img_104"),
    Pokemon(id: 105, name: "marowak", types: [.ground], imageName:"img_105"),
    Pokemon(id: 106, name: "hitmonlee", types: [.fighting], imageName:"img_106"),
    Pokemon(id: 107, name: "hitmonchan", types: [.fighting], imageName:"img_107"),
    Pokemon(id: 108, name: "lickitung", types: [.normal], imageName:"img_108"),
    Pokemon(id: 109, name: "koffing", types: [.poison], imageName:"img_109"),
    Pokemon(id: 110, name: "weezing", types: [.poison], imageName:"img_110"),
    Pokemon(id: 111, name: "rhyhorn", types: [.ground, .rock], imageName:"img_111"),
    Pokemon(id: 112, name: "rhydon", types: [.ground, .rock], imageName:"img_112"),
    Pokemon(id: 113, name: "chansey", types: [.normal], imageName:"img_113"),
    Pokemon(id: 114, name: "tangela", types: [.grass], imageName:"img_114"),
    Pokemon(id: 115, name: "kangaskhan", types: [.normal], imageName:"img_115"),
    Pokemon(id: 116, name: "horsea", types: [.water], imageName:"img_116"),
    Pokemon(id: 117, name: "seadra", types: [.water], imageName:"img_117"),
    Pokemon(id: 118, name: "goldeen", types: [.water], imageName:"img_118"),
    Pokemon(id: 119, name: "seaking", types: [.water], imageName:"img_119"),
    Pokemon(id: 120, name: "staryu", types: [.water], imageName:"img_120"),
    Pokemon(id: 121, name: "starmie", types: [.water, .psychic], imageName:"img_121"),
    Pokemon(id: 122, name: "mr-mime", types: [.psychic, .fairy], imageName:"img_122"),
    Pokemon(id: 123, name: "scyther", types: [.bug, .flying], imageName:"img_123"),
    Pokemon(id: 124, name: "jynx", types: [.ice, .psychic], imageName:"img_124"),
    Pokemon(id: 125, name: "electabuzz", types: [.electric], imageName:"img_125"),
    Pokemon(id: 126, name: "magmar", types: [.fire], imageName:"img_126"),
    Pokemon(id: 127, name: "pinsir", types: [.bug], imageName:"img_127"),
    Pokemon(id: 128, name: "tauros", types: [.normal], imageName:"img_128"),
    Pokemon(id: 129, name: "magikarp", types: [.water], imageName:"img_129"),
    Pokemon(id: 130, name: "gyarados", types: [.water, .flying], imageName:"img_130"),
    Pokemon(id: 131, name: "lapras", types: [.water, .ice], imageName:"img_131"),
    Pokemon(id: 132, name: "ditto", types: [.normal], imageName:"img_132"),
    Pokemon(id: 133, name: "eevee", types: [.normal], imageName:"img_133"),
    Pokemon(id: 134, name: "vaporeon", types: [.water], imageName:"img_134"),
    Pokemon(id: 135, name: "jolteon", types: [.electric], imageName:"img_135"),
    Pokemon(id: 136, name: "flareon", types: [.fire], imageName:"img_136"),
    Pokemon(id: 137, name: "porygon", types: [.normal], imageName:"img_137"),
    Pokemon(id: 138, name: "omanyte", types: [.rock, .water], imageName:"img_138"),
    Pokemon(id: 139, name: "omastar", types: [.rock, .water], imageName:"img_139"),
    Pokemon(id: 140, name: "kabuto", types: [.rock, .water], imageName:"img_140"),
    Pokemon(id: 141, name: "kabutops", types: [.rock, .water], imageName:"img_141"),
    Pokemon(id: 142, name: "aerodactyl", types: [.rock, .flying], imageName:"img_142"),
    Pokemon(id: 143, name: "snorlax", types: [.normal], imageName:"img_143"),
    Pokemon(id: 144, name: "articuno", types: [.ice, .flying], imageName:"img_144"),
    Pokemon(id: 145, name: "zapdos", types: [.electric, .flying], imageName:"img_145"),
    Pokemon(id: 146, name: "moltres", types: [.fire, .flying], imageName:"img_146"),
    Pokemon(id: 147, name: "dratini", types: [.dragon], imageName:"img_147"),
    Pokemon(id: 148, name: "dragonair", types: [.dragon], imageName:"img_148"),
    Pokemon(id: 149, name: "dragonite", types: [.dragon, .flying], imageName:"img_149"),
    Pokemon(id: 150, name: "mewtwo", types: [.psychic], imageName:"img_150"),
    Pokemon(id: 151, name: "mew", types: [.psychic], imageName:"img_151")
]
